/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class daas_LedNotificationService */

#ifndef _Included_daas_LedNotificationService
#define _Included_daas_LedNotificationService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     daas_LedNotificationService
 * Method:    send
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_daas_LedNotificationService_send
  (JNIEnv *, jobject);

/*
 * Class:     daas_LedNotificationService
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_daas_LedNotificationService_init
  (JNIEnv *, jobject);

/*
 * Class:     daas_LedNotificationService
 * Method:    ismessageable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_daas_LedNotificationService_ismessageable
  (JNIEnv *, jobject);

/*
 * Class:     daas_LedNotificationService
 * Method:    message
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_daas_LedNotificationService_message
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif


